{*** Configuration ***}

{$DEFINE Int32ValidateThorough}       // Enable to perform complete LongInt validation

{$DEFINE Int64ValidateThorough}       // Enable to perform more thorough Int64 validation

{$DEFINE PriorityChange}                // Disable to remove priority change. KEEP ENABLED IN VERSIONS USED FOR BENCHMARKING!

{$DEFINE ReportSpread}                  // Disable to not include spread in report

//{$DEFINE ThreadSafe}                  // Enable to make benchmark threadsafe (not needed for now).


